### ISSUE TITLE
F5 Bug

### ISSUE THREAD

**Issue by IkaOnCrack** [Rubyboat1207/ghost#1]
Hey Ruby! I've downloaded your ghostblock mod recently. The mod is perfect however I've noticed that there is a bug in the mod. When you go into F5 mode, your pov is inside your skin (as shown below).

![image](https://user-images.githubusercontent.com/99002325/212710413-e3cd9609-2b9e-42ae-ab70-6dfd5fa9377d.png)
![image](https://user-images.githubusercontent.com/99002325/212710436-836e38de-6784-4e3c-8165-d3ae49708515.png)

**Comment by Rubyboat1207** [comment]
Oh, that must be because the "Zoom out Camera Distance" value is set to 0, try setting it to 4 and it should look like normal! Does that fix it?

**Comment by IkaOnCrack** [comment]
Yeah it worked. Thanks man.
