### ISSUE TITLE
Will there be 1.20.4 version? This mod is too cool!

### ISSUE THREAD

**Issue by Deykii** [Rubyboat1207/ghost#4]

**Comment by Rubyboat1207** [comment]
Know what, sure. I'll start working on it soon. At this point it'll probably be 1.20.6

**Comment by Deykii** [comment]
> Know what, sure. I'll start working on it soon. At this point it'll probably be 1.20.6

😎

**Comment by Rubyboat1207** [comment]
Thanks for getting me to revive this project for the latest version!
