### ISSUE TITLE
Move the "ghost_config.json" to the "config" folder

### ISSUE THREAD

**Issue by farneser** [Rubyboat1207/ghost#7]
I didn't find the config file and went to surs to find the name of the config, parsed what is there and write a json file myself to then notice that the config file is not in the config folder and all this time it was already there, why is it in root is located 

All you need to do is just change few lines and the config file will be with the rest of the configs, not in the root of minecraft.

Just replace PATH [here](https://github.com/Rubyboat1207/ghost/blob/main/src/main/java/rubyboat/ghost/config/Config.java#L23)

```java
static String path = "config/ghost_config.json";
```

And create config folder if not exists in `loadConfig` method [here](https://github.com/Rubyboat1207/ghost/blob/main/src/main/java/rubyboat/ghost/config/Config.java#L192)

replace this code

```java
Files.writeString(Path.of(path), getFallbackConfig().toString());
```
for this code

```java
Path filePath = Paths.get(path);
Files.createDirectories(filePath.getParent());
Files.writeString(filePath, getFallbackConfig().toString());
```

**Comment by Rubyboat1207** [comment]
Sounds good to me, do you have a PR or something you want me to merge? If not, I can make the changes myself, considering you've already written the code for me. Also - how about compatibility with previous versions? If you decide to make a PR, please include searching in the root, and moving the old file into config folder. If you dont decide to make a PR, ill make the change when i can this week.

**Comment by farneser** [comment]
PR is here #8

**Comment by Rubyboat1207** [comment]
I'll build for modrinth soon
